training: !!bool "true"
# training: !!bool "false"
device: "cuda"
unprocessed_data: 'SLURM_TMPDIR/data/*/*/*/*.wav'
---
data:
    train_path: 'SLURM_TMPDIR/train_tisv'
    train_path_unprocessed: 'SLURM_TMPDIR/data/TRAIN/*/*/*.wav'
    test_path: 'SLURM_TMPDIR/test_tisv'
    test_path_unprocessed: 'SLURM_TMPDIR/data/TEST/*/*/*.wav'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
    alpha: 0.5 #for mixing
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: 'SLURM_TMPDIR/model.model' #Model path for testing, inference, or resuming training
    # model_path: 'SLURM_TMPDIR/speech_mix_id_checkpoint/final_epoch_950_batch_id_141.model'
    # model_path: 'speech_id_checkpoint/final_epoch_950_batch_id_141.model'
---
train:
    N : 4 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    lr: 0.01 
    epochs: 950 #Max training speaker epoch 
    log_interval: 30 #Epochs before printing progress
    log_file: 'SLURM_TMPDIR/speech_mix_id_checkpoint/Stats'
    checkpoint_interval: 120 #Save model after x speaker epochs
    checkpoint_dir: 'SLURM_TMPDIR/speech_mix_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 4 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 1 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
